<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.SumRequest</code>
 */
class SumRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 number1 = 1;</code>
     */
    protected $number1 = 0;
    /**
     * Generated from protobuf field <code>int32 number2 = 2;</code>
     */
    protected $number2 = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $number1
     *     @type int $number2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Simple::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 number1 = 1;</code>
     * @return int
     */
    public function getNumber1()
    {
        return $this->number1;
    }

    /**
     * Generated from protobuf field <code>int32 number1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNumber1($var)
    {
        GPBUtil::checkInt32($var);
        $this->number1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number2 = 2;</code>
     * @return int
     */
    public function getNumber2()
    {
        return $this->number2;
    }

    /**
     * Generated from protobuf field <code>int32 number2 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNumber2($var)
    {
        GPBUtil::checkInt32($var);
        $this->number2 = $var;

        return $this;
    }

}

